src/dnceng/src/DotNet.Status.Web/DotNet.Status.Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using System.IO;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DotNet.Status.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken(Order = 1001)]
public class ErrorModel : PageModel
{
    public string RequestId { get; set; }
    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    public string Referrer { get; set; }
    public bool ShowReferrer => !string.IsNullOrEmpty(Referrer);

    public string ExceptionMessage { get; set; }
    public bool ShowExceptionMessage => !string.IsNullOrEmpty(ExceptionMessage);

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        Referrer = HttpContext.Request.Headers["referer"];

        // Do NOT expose sensitive error information directly to the client.
        #region snippet_ExceptionHandlerPathFeature
        var exceptionHandlerPathFeature =
            HttpContext.Features.Get<IExceptionHandlerPathFeature>();
        if (exceptionHandlerPathFeature?.Error is FileNotFoundException)
        {
            ExceptionMessage = "File error thrown";
        }
        if (exceptionHandlerPathFeature?.Path == "/index")
        {
            ExceptionMessage += " from home page";
        }
        #endregion
    }
}

src/dnceng/src/DotNet.Status.Web/DotNet.Status.Web/Pages/Routes.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using Newtonsoft.Json;

namespace HelixAPI.Pages;

public class RoutesModel : PageModel
{
    private readonly IActionDescriptorCollectionProvider _actionDescriptorCollectionProvider;
    private readonly IHostEnvironment _environment;

    public RoutesModel(IActionDescriptorCollectionProvider actionDescriptorCollectionProvider, IHostEnvironment environment)
    {
        this._actionDescriptorCollectionProvider = actionDescriptorCollectionProvider;
        _environment = environment;
    }

    public List<RouteInfo> Routes { get; set; }

    public IActionResult OnGet()
    {
        if (!_environment.IsDevelopment())
        {
            return NotFound();
        }
        Routes = _actionDescriptorCollectionProvider.ActionDescriptors.Items
            .Select(x => new RouteInfo
            {
                Action = x.RouteValues["Action"],
                Controller = x.RouteValues["Controller"],
                Page = x.RouteValues["Page"],
                Name = x.AttributeRouteInfo?.Name,
                Template = x.AttributeRouteInfo?.Template,
                Constraint = x.ActionConstraints == null ? "" : JsonConvert.SerializeObject(x.ActionConstraints)
            })
            .OrderBy(r => r.Template)
            .ToList();

        return Page();
    }

    public class RouteInfo
    {
        public string Template { get; set; }
        public string Name { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Constraint { get; set; }
        public string Page { get; set; }
    }
}

src/dnceng/src/DotNet.Status.Web/DotNet.Status.Web/Pages/Status.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DotNet.Status.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken(Order = 1001)]
public class StatusModel : PageModel
{
}

src/dnceng/src/DotNet.Status.Web/DotNet.Status.Web/Pages/Token.cshtml.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using DotNet.Status.Web;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.DotNet.Web.Authentication.GitHub;

namespace DotNet.Status.Web.Pages;

public class TokenModel : PageModel
{
    private readonly ITokenStore _tokens;
    private readonly ITokenRevocationProvider _revocation;
    private readonly GitHubUserTokenHandler _handler;
    private readonly GitHubClaimResolver _resolver;

    public TokenModel(
        ITokenStore tokens,
        ITokenRevocationProvider revocation,
        GitHubUserTokenHandler handler,
        GitHubClaimResolver resolver)
    {
        _tokens = tokens;
        _revocation = revocation;
        _handler = handler;
        _resolver = resolver;
    }

    public string TokenValue { get; set; }

    [BindProperty]
    public string Description { get; set; }

    [BindProperty]
    public long RevokeTokenId { get; set; }

    public void OnGet()
    {
    }

    public async Task OnPostNewToken()
    {
        StoredTokenData token = await _tokens.IssueTokenAsync(
            UserId,
            DateTimeOffset.UtcNow.AddYears(1),
            Description);

        TokenValue = _handler.EncodeToken(User, token);
    }

    private long UserId => long.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);

    public async Task<IActionResult> OnPostRevoke()
    {
        await _revocation.RevokeTokenAsync(UserId, RevokeTokenId);
        return Redirect(Request.Path);
    }
}

src/dnceng/src/DotNet.Status.Web/DotNet.Status.Web/Pages/Index.cshtml
@page
@using System.Security.Claims
@{
    ViewData["Title"] = "Home page";
}

.NET Engineering Status Reporting endpoint

To get/set tokens, go to <a href="@Url.Page("Token")">Tokens</a>


<div>
    @if (User.Identity.IsAuthenticated)
    {
        <div>Roles for @User.Identity.Name</div>
        <ul>
            @foreach (Claim role in User.FindAll(ClaimTypes.Role))
            {
                <li>@role.Value</li>
            }
        </ul>
    }
    else
    {
        <a href="/signin">Sign in</a>
    }
</div>

src/dnceng/src/DotNet.Status.Web/DotNet.Status.Web/Pages/Routes.cshtml
@page
@model HelixAPI.Pages.RoutesModel
@{
    ViewData["Title"] = "Routes";
}

<h2>@ViewData["Title"]</h2>
<h3>Route Debug Info</h3>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Route Template</th>
            <th>Target</th>
            <th>Constraints/Verbs</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var route in Model.Routes)
        {
            @if (!String.IsNullOrEmpty(route.Template))
            {
                <tr>
                    <td>@route.Template</td>
                    @if (string.IsNullOrEmpty(route.Page))
                    {
                        <td>Controller @route.Controller, Action @route.Action</td>
                    }
                    else
                    {
                        <td>Page @route.Page</td>
                    }
                    <td>@route.Constraint</td>
                    <td>@route.Name</td>
                </tr>
            }
        }
    </tbody>
</table>

src/dnceng/src/DotNet.Status.Web/DotNet.Status.Web/Pages/Status.cshtml
@page
@model DotNet.Status.Web.Pages.StatusModel
@{
    Layout = null;
}

@if (Request.Headers["Accept"].ToString().StartsWith("application/json"))
{
    @switch (@Request.Query["code"].ToString())
    {
        case "404":
            @Html.Raw("{\"message\":\"Not Found\"}");
            break;
        case "403":
            @Html.Raw("{\"message\":\"Unauthorized\"}");
            break;
        case "401":
            @Html.Raw("{\"message\":\"Authorization Required\"}");
            break;
        default:
            @Html.Raw("{\"message\":\"Unknown error\"}");
            break;

    }
}
else
{

    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        @switch (@Request.Query["code"].ToString())
        {
            case "404":
                <title>Not Found</title>
                break;
            case "403":
                <title>Unauthorized</title>
                break;
            case "401":
                <title>Authorization Required</title>
                break;
            default:
                <title>Error</title>
                break;

        }
    </head>
    <body>
        @switch (Request.Query["code"].ToString())
        {
            case "404":
                <h1>404 Not found</h1>
                break;
            case "403":
                <h1>403 Unauthorized</h1>
                break;
            case "401":
                <h1>401 Authorization Required</h1>
                break;
            default:
                <h1>Error</h1>
                break;

        }
    </body>
</html>
}

src/dnceng/src/DotNet.Status.Web/DotNet.Status.Web/Pages/Token.cshtml
@page
@inject ITokenStore tokens
@using System.Security.Claims
@using DotNet.Status.Web
@model DotNet.Status.Web.Pages.TokenModel
@{
    ViewData["Title"] = "Tokens";
    string userIdString = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
    long userId = long.TryParse(userIdString, out var temp) ? temp : 0;

    string GetStyle(StoredTokenData tok)
    {
        if (tok.RevocationStatus != RevocationStatus.Active)
        {
            return "color:pink;font-style:italic";
        }

        if (tok.Expiration < DateTimeOffset.UtcNow)
        {
            return "color:grey;font-style:italic";
        }

        return "";
    }

}

@if (!string.IsNullOrEmpty(Model.TokenValue))
{
    <div style="background-color: pink">
        <div>New token value, this will not be redisplayed, save this!</div>
        <div>@Model.TokenValue</div>
    </div>
}

<table>
    <tr style="font-style: ">
        <th>Description</th>
        <th>Issued</th>
        <th>Expiration</th>
        <th>Revoke</th>
    </tr>
    @foreach (StoredTokenData token in await tokens.GetTokensForUserAsync(userId, HttpContext.RequestAborted))
    {
        <tr style="@GetStyle(token)">
            <td style="vertical-align: middle">@token.Description</td>
            <td style="vertical-align: middle">@token.Issued.ToString("d")</td>
            <td style="vertical-align: middle">@token.Expiration.ToString("d")</td>
            @if (token.RevocationStatus != RevocationStatus.Active)
            {
                <td style="vertical-align: middle">revoked</td>
            } else if (token.Expiration < DateTimeOffset.UtcNow)
            {
                <td style="vertical-align: middle">expired</td>
            }
            else
            {
                <td style="vertical-align: middle">
                    <form asp-page-handler="Revoke" style="margin: 0">
                        <input type="hidden" asp-for="RevokeTokenId" value="@token.TokenId"/>
                        <button type="submit">Revoke</button>
                    </form>
                </td>
            }
        </tr>
    }
</table>

<form asp-page-handler="NewToken" method="post">
    <input asp-for="Description" /> <button type="submit">New Token</button>
</form>

src/dnceng/src/DotNet.Status.Web/DotNet.Status.Web/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
</head>

<body>
<div>
    @RenderBody()
</div>
<footer>
    <hr/>
    <div>
        <a href="mailto:dnceng@microsoft.com">Contact Us</a>
        &nbsp;|&nbsp;
        <a href="https://go.microsoft.com/fwlink/?LinkId=521839">Privacy &amp; Cookies</a>
        &nbsp;|&nbsp;
        <a href="https://go.microsoft.com/fwlink/?LinkID=206977">Terms of Use</a>
        &nbsp;|
        &copy; 2020 Microsoft
    </div>
</footer>
</body>

</html>